<?php \dawfony\Ti::extend("view/MainView.phtml"); ?>
<?php \dawfony\Ti::startBlock("content"); ?>
<?php if (isset($data['error'])) {?>
<div class="alert alert-danger" role="alert">
  <?=$data['error']?>
</div>
<?php }?>
<form action="Login" method="POST">
  <div class="form-group">
    <label for="login">Login:</label>
    <input type="text" class="form-control" id="login" name="login">
  </div>
  <div class="form-group">
    <label for="contrasenha">Contraseña:</label>
    <input type="password" class="form-control" id="contrasenha" name="contrasenha">
  </div>
  <button type="submit" class="btn btn-success">Iniciar Sesion</button>
</form>
<?php \dawfony\Ti::endBlock(); ?>
<?php \dawfony\Ti::endExtend(); ?>