<?php global $URL_PATH;?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <?php \dawfony\Ti::startBlock("extrahead"); ?>
    <?php \dawfony\Ti::endBlock() ?>
    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        <?=$data["title"]?> - SocialDAW
        <?php \dawfony\Ti::endBlock() ?>
    </title>
</head>

<body class="container">
    <div class="text-center">
        <img src="<?=$URL_PATH?>/media/logo.png" class="rounded" alt="logo">
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?=$URL_PATH?>">Lo último</a>
                </li>
                <?php if (isset($_SESSION["login"])) : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$URL_PATH?>/Seguidos">Seguidos</a>
                    </li>
                <?php endif; ?>
                <li class="nav-item">
                    <?php if (!isset($_SESSION["rol"])) { ?>
                        <a class="nav-link" href="<?=$URL_PATH?>/Registrate">Registrate</a>
                    <?php } else {?>
                        <a class="nav-link" href="<?=$URL_PATH?>/Perfil/<?=$_SESSION['login']?>">Mi Perfil</a>
                    <?php } ?>
                </li>
                <li class="nav-item">
                    <?php if (!isset($_SESSION["rol"])) { ?>
                        <a class="nav-link" href="<?=$URL_PATH?>/Login">Login</a>
                    <?php } else {?>
                        <a class="nav-link" href="<?=$URL_PATH?>/CerrarSesion">Cerrar Sesion</a>
                    <?php } ?>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="filtrar">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Filtrar!</button>
            </form>
        </div>
    </nav>
    <div>
        <?php \dawfony\Ti::startBlock("content"); ?>
        <?php \dawfony\Ti::endBlock() ?>
    </div>
</body>
</html>