<?php global $URL_PATH;?>
<?php \dawfony\Ti::extend("view/MainView.phtml"); ?>
<?php \dawfony\Ti::startBlock("content"); ?>
<div class="row m-2">
    <div class="col-5">
        <img class="img-fluid rounded" src="<?= $URL_PATH ?>/media/<?= $post->foto ?>" alt="Imagen: <?= $post->resumen ?>">
    </div>
    <div class="col-7">
        <h4><?= $post->resumen ?></h4>
        <?php /*Pasamos el id del post al evento de javascript. Enlace solo si usuario logueado*/ ?>
        <?php if (isset($_SESSION["login"])) : ?>
            <a href="javascript:void(0)" onclick="likeClicked(<?= $post->id ?>)">
            <?php endif ?>
            <?php /* El atributo id del elemento del corazón tiene como sufijo el id del post */ ?>
            <i id="likecorazon<?= $post->id ?>" class="fa fa-heart<?= ($post->like ? " text-danger" : "") ?>"></i>
            <?php if (isset($_SESSION["login"])) : ?>
            </a>
        <?php endif ?>
        <?php /* Lo mismo para el elemento que contiene la cuenta de likes:
                             su atributo id contiene como sufijo el id del post */ ?>
        <span id="likecontador<?= $post->id ?>">
            <?= $post->numLikes ?>
        </span>
        <a href="#comentarios"><i class="fa fa-comments"></i> <?= $post->numComentarios ?></a>
        <div>
            Por <a href="<?= $URL_PATH ?>/Perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a>
            en <em><?= $post->categoria ?></em>
            el <?= $post->fecha ?>
        </div>
        <hr>
        <div>
        <?= $post->texto; ?>
        </div>
    </div>
</div>
<?php if (isset($_SESSION["rol"]) && $_SESSION["rol"] == 1) :?>
<a href="<?=$URL_PATH?>/Admin/borrarpost/<?=$post->id?>" class="btn btn-danger btn-sm">
Eliminar Post</a>
<?php endif ?>
<hr>
<?php require "Comentarios.phtml"; ?>
<script>
var URL_PATH = '<?= $URL_PATH ?>'
</script>
<script src="<?= $URL_PATH ?>/js/like.js"></script>
<?php \dawfony\Ti::endBlock(); ?>
<?php \dawfony\Ti::endExtend(); ?>